#!/bin/sh

export DO_TOKEN=""
# [nyc1, nyc3, sfo2, ams3, sgp1, lon1, fra1, tor1, blr1]
export DROPLET_REGION=""
# select your port where server provide shadowsocks service
export SERVER_PORT=
# set your own shadowsocks password
export PASSWORD=""
# set finger print if has ssh key set
export FINGERPRINT=""

if [ "$OSTYPE" = "linux-gnu" ]; then
  echo "no implementation found for this"
elif [[ "$OSTYPE" = "darwin"* ]]; then
  # Mac OSX
  source ./create-server-mac
elif [ "$OSTYPE" = "cygwin" ]; then
  # POSIX compatibility layer and Linux environment emulation for Windows
  echo "no implementation found for this"
elif [ "$OSTYPE" = "msys" ]; then
  # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
  echo "no implementation found for this"
elif [ "$OSTYPE" = "freebsd"* ]; then
  # ...
  echo "no implementation found for this"
else
  # Unknown.
  echo "no implementation found for this"
fi
