#!/bin/sh

echo $OSTYPE

DO_TOKEN=""
# [nyc1, nyc3, sfo2, ams3, sgp1, lon1, fra1, tor1, blr1]
DROPLET_REGION=""
# select your port where server provide shadowsocks service
SERVER_PORT=
# set your own shadowsocks password
PASSWORD=""
# set finger print if has ssh key set
FINGERPRINT=""

if [[ "$OSTYPE" == "linux-gnu" ]]; then

elif [[ "$OSTYPE" == "darwin"* ]]; then
  # Mac OSX
  source ./create-server-mac
elif [[ "$OSTYPE" == "cygwin" ]]; then
  # POSIX compatibility layer and Linux environment emulation for Windows
elif [[ "$OSTYPE" == "msys" ]]; then
  # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
elif [[ "$OSTYPE" == "freebsd"* ]]; then
  # ...
else
  # Unknown.
fi
